# Generated by Django 6.0.4 on 2026-04-30 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='NoConformidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('fecha_apertura', models.DateField()),
                ('origen', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('gravedad', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('producto_proceso_afectado', models.CharField(max_length=100)),
                ('responsable', models.ManyToManyField(related_name='seguimiento', to='Gestion_NC.responsable')),
            ],
        ),
        migrations.CreateModel(
            name='AccionCorrectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_prevista', models.DateField()),
                ('fecha_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('nc_asociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_NC.noconformidad')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_NC.responsable')),
            ],
        ),
    ]
