# Generated by Django 6.0.4 on 2026-04-30 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_NC', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noconformidad',
            options={'verbose_name': 'NoConformidad', 'verbose_name_plural': 'NoConformidades'},
        ),
    ]
