# Generated by Django 6.0.4 on 2026-04-30 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_NC', '0002_alter_noconformidad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noconformidad',
            options={'verbose_name': 'NoConformidad'},
        ),
    ]
