# Generated by Django 6.0.4 on 2026-04-30 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_NC', '0003_alter_noconformidad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accioncorrectiva',
            options={'verbose_name': 'AccionCorrectiva', 'verbose_name_plural': 'AccionCorrectiva'},
        ),
        migrations.AlterModelOptions(
            name='noconformidad',
            options={'verbose_name': 'NoConformidad', 'verbose_name_plural': 'NoConformidad'},
        ),
        migrations.AlterModelOptions(
            name='responsable',
            options={'verbose_name': 'Responsable', 'verbose_name_plural': 'Responsable'},
        ),
    ]
